---
name: build nodejs app
on:
  workflow_dispatch:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master

jobs:
  job1:
    runs_on: ubuntu-latest
    steps:
    - name: clone the repo
      uses: action/checkout@v6
    - name: Install nodejs
      uses: action/setup-nodejs@v6
      with:
        node-version: 18
        cache: 'npm'
    - name: Install node dependencies
      run: npm ci
    - name: Execute Test
      run: npm test
    - name: Build the nodejs code
      run: npm run build
